/* OpenCL source for the quad-fitting stage: one work-item per cluster,
 * replaying the CPU fit_quad pipeline exactly (same float/double
 * operation order; compiled with FP_CONTRACT OFF and correctly-rounded
 * fp32 divide/sqrt so every step is the same exact-rounded operation).
 * Included by apriltag_opencl.c as a second program source string. */
#pragma once

static const char *KSRC_QUAD =
"#pragma OPENCL FP_CONTRACT OFF\n"
"\n"
"typedef struct { ushort x, y; short gx, gy; } cpt_t;\n"
"\n"
"typedef struct { float p[4][2]; int valid; int reversed; } quad_out_t;\n"
"\n"
"typedef struct { double err, mse; double params[4]; int computed, pad; } pair_fit_t;\n"
"\n"
"/* order-preserving float-bits key, as on the CPU */\n"
"inline uint fq_slope_key(float slope)\n"
"{\n"
"    uint u = as_uint(slope);\n"
"    return u ^ ((uint)((int)u >> 31) | 0x80000000u);\n"
"}\n"
"\n"
"/* <=5 sorting networks; compare high words only, no swap on ties */\n"
"inline void fq_network(global ulong *k, int sz)\n"
"{\n"
"#define MAYBE_SWAP(a, b) \\\n"
"    if ((k[a] >> 32) > (k[b] >> 32)) { ulong t = k[a]; k[a] = k[b]; k[b] = t; }\n"
"    if (sz <= 1) return;\n"
"    if (sz == 2) { MAYBE_SWAP(0,1); return; }\n"
"    if (sz == 3) { MAYBE_SWAP(0,1); MAYBE_SWAP(1,2); MAYBE_SWAP(0,1); return; }\n"
"    if (sz == 4) { MAYBE_SWAP(0,1); MAYBE_SWAP(2,3); MAYBE_SWAP(0,2);\n"
"                   MAYBE_SWAP(1,3); MAYBE_SWAP(1,2); return; }\n"
"    MAYBE_SWAP(0,1); MAYBE_SWAP(3,4); MAYBE_SWAP(1,2); MAYBE_SWAP(0,1);\n"
"    MAYBE_SWAP(0,3); MAYBE_SWAP(2,4); MAYBE_SWAP(1,2); MAYBE_SWAP(2,3);\n"
"    MAYBE_SWAP(1,2);\n"
"#undef MAYBE_SWAP\n"
"}\n"
"\n"
"/* merge with the CPU tie rule: take A only on strictly-less */\n"
"inline void fq_merge(global const ulong *as, int asz, global const ulong *bs, int bsz,\n"
"                     global ulong *out)\n"
"{\n"
"    int ap = 0, bp = 0, op = 0;\n"
"    while (ap < asz && bp < bsz) {\n"
"        ulong av = as[ap], bv = bs[bp];\n"
"        int ta = av < bv;\n"
"        out[op++] = ta ? av : bv;\n"
"        ap += ta;\n"
"        bp += !ta;\n"
"    }\n"
"    while (ap < asz) out[op++] = as[ap++];\n"
"    while (bp < bsz) out[op++] = bs[bp++];\n"
"}\n"
"\n"
"/* The CPU ping-pong merge sort (keysort_in_place/keysort_move) as an\n"
" * explicit-stack iteration: same splits, same <=5 leaf networks, same\n"
" * merge comparisons -- the sorted array is bit-identical, including\n"
" * the inconsistent leaf-vs-merge tie behavior. */\n"
"inline void fq_keysort(global ulong *A, global ulong *B, int sz)\n"
"{\n"
"    if (sz < 2)\n"
"        return;\n"
"    struct { int off, sz; char mode, phase; } st[40];\n"
"    int top = 0;\n"
"    st[0].off = 0; st[0].sz = sz; st[0].mode = 0; st[0].phase = 0; // 0 = in place\n"
"    while (top >= 0) {\n"
"        int off = st[top].off, n = st[top].sz;\n"
"        char mode = st[top].mode;\n"
"        if (n <= 5) {\n"
"            fq_network(A + off, n);\n"
"            if (mode) {\n"
"                for (int i = 0; i < n; i++) B[off + i] = A[off + i];\n"
"            }\n"
"            top--;\n"
"            continue;\n"
"        }\n"
"        int asz = n / 2;\n"
"        if (st[top].phase == 0) {\n"
"            st[top].phase = 1;\n"
"            top++;\n"
"            st[top].off = off; st[top].sz = asz;\n"
"            st[top].mode = !mode; st[top].phase = 0;\n"
"        } else if (st[top].phase == 1) {\n"
"            st[top].phase = 2;\n"
"            top++;\n"
"            st[top].off = off + asz; st[top].sz = n - asz;\n"
"            st[top].mode = !mode; st[top].phase = 0;\n"
"        } else {\n"
"            if (!mode) // children moved into B; merge back into A\n"
"                fq_merge(B + off, asz, B + off + asz, n - asz, A + off);\n"
"            else       // children sorted in A; merge into B\n"
"                fq_merge(A + off, asz, A + off + asz, n - asz, B + off);\n"
"            top--;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"typedef struct {\n"
"    global double *Mx, *My, *Mxx, *Mxy, *Myy, *W;\n"
"} fq_lfps;\n"
"\n"
"inline void fq_fit_line(const fq_lfps *L, int sz, int i0, int i1,\n"
"                        double *lineparm, double *err, double *mse)\n"
"{\n"
"    double Mx, My, Mxx, Myy, Mxy, W;\n"
"    int N;\n"
"    if (i0 < i1) {\n"
"        N = i1 - i0 + 1;\n"
"        Mx = L->Mx[i1]; My = L->My[i1]; Mxx = L->Mxx[i1];\n"
"        Mxy = L->Mxy[i1]; Myy = L->Myy[i1]; W = L->W[i1];\n"
"        if (i0 > 0) {\n"
"            Mx -= L->Mx[i0-1]; My -= L->My[i0-1]; Mxx -= L->Mxx[i0-1];\n"
"            Mxy -= L->Mxy[i0-1]; Myy -= L->Myy[i0-1]; W -= L->W[i0-1];\n"
"        }\n"
"    } else {\n"
"        Mx  = L->Mx[sz-1]  - L->Mx[i0-1];  My  = L->My[sz-1]  - L->My[i0-1];\n"
"        Mxx = L->Mxx[sz-1] - L->Mxx[i0-1]; Mxy = L->Mxy[sz-1] - L->Mxy[i0-1];\n"
"        Myy = L->Myy[sz-1] - L->Myy[i0-1]; W   = L->W[sz-1]   - L->W[i0-1];\n"
"        Mx += L->Mx[i1]; My += L->My[i1]; Mxx += L->Mxx[i1];\n"
"        Mxy += L->Mxy[i1]; Myy += L->Myy[i1]; W += L->W[i1];\n"
"        N = sz - i0 + i1 + 1;\n"
"    }\n"
"    double Ex = Mx / W;\n"
"    double Ey = My / W;\n"
"    double Cxx = Mxx / W - Ex*Ex;\n"
"    double Cxy = Mxy / W - Ex*Ey;\n"
"    double Cyy = Myy / W - Ey*Ey;\n"
"    // sqrtf semantics: round to float, float sqrt, widen back\n"
"    double root = (double)sqrt((float)((Cxx - Cyy)*(Cxx - Cyy) + 4*Cxy*Cxy));\n"
"    double eig_small = 0.5*(Cxx + Cyy - root);\n"
"    if (lineparm) {\n"
"        lineparm[0] = Ex;\n"
"        lineparm[1] = Ey;\n"
"        double eig = 0.5*(Cxx + Cyy + root);\n"
"        double nx1 = Cxx - eig, ny1 = Cxy;\n"
"        double M1 = nx1*nx1 + ny1*ny1;\n"
"        double nx2 = Cxy, ny2 = Cyy - eig;\n"
"        double M2 = nx2*nx2 + ny2*ny2;\n"
"        double nx, ny, M;\n"
"        if (M1 > M2) { nx = nx1; ny = ny1; M = M1; }\n"
"        else { nx = nx2; ny = ny2; M = M2; }\n"
"        double length = (double)sqrt((float)M);\n"
"        if (fabs(length) < 1e-12) {\n"
"            lineparm[2] = lineparm[3] = 0;\n"
"        } else {\n"
"            lineparm[2] = nx/length;\n"
"            lineparm[3] = ny/length;\n"
"        }\n"
"    }\n"
"    if (err) *err = N*eig_small;\n"
"    if (mse) *mse = eig_small;\n"
"}\n"
"\n"
"kernel void fit_quads_k(global const cpt_t *pts, global const uint *coff,\n"
"                        global const uint *csz, uint ncl,\n"
"                        global const uint *elig_scr, // per-cluster scratch point offset, ~0u = skip\n"
"                        global const uint *elig_ord, // per-cluster eligible ordinal (memo slot)\n"
"                        global const uchar *im, int iw, int ih, int istride,\n"
"                        int tag_width, int normal_border, int reversed_border,\n"
"                        int max_nmaxima, double max_line_fit_mse, double max_dot,\n"
"                        global const double *qsm_kernel, // 7 taps, host-computed\n"
"                        global ulong *g_keys, global ulong *g_tmp,\n"
"                        global double *g_lf, // 6 arrays interleaved by slab\n"
"                        ulong lf_stride,     // points capacity of one lf array\n"
"                        global double *g_errs, global double *g_yfilt,\n"
"                        global int *g_maxima, global double *g_maxerrs,\n"
"                        global pair_fit_t *g_memo, // 16x16 per eligible cluster\n"
"                        global quad_out_t *out)\n"
"{\n"
"    uint ci = get_global_id(0);\n"
"    if (ci >= ncl) return;\n"
"    out[ci].valid = 0;\n"
"    uint scr = elig_scr[ci];\n"
"    if (scr == 0xffffffffu) return; // gate-failing cluster\n"
"    int sz = (int)csz[ci];\n"
"    global const cpt_t *cp = pts + coff[ci];\n"
"\n"
"    // bounding box\n"
"    ushort xmax = cp[0].x, xmin = cp[0].x, ymax = cp[0].y, ymin = cp[0].y;\n"
"    for (int i = 1; i < sz; i++) {\n"
"        ushort px = cp[i].x, py = cp[i].y;\n"
"        if (px > xmax) xmax = px; else if (px < xmin) xmin = px;\n"
"        if (py > ymax) ymax = py; else if (py < ymin) ymin = py;\n"
"    }\n"
"    if ((int)(xmax - xmin) * (int)(ymax - ymin) < tag_width) return;\n"
"\n"
"    float cx = (xmin + xmax) * 0.5f + 0.05118f;\n"
"    float cy = (ymin + ymax) * 0.5f + -0.028581f;\n"
"    float dot = 0;\n"
"\n"
"    global ulong *keys = g_keys + scr;\n"
"    global ulong *tmp = g_tmp + scr;\n"
"    for (int i = 0; i < sz; i++) {\n"
"        float dx = cp[i].x - cx;\n"
"        float dy = cp[i].y - cy;\n"
"        dot += dx*cp[i].gx + dy*cp[i].gy;\n"
"        float quadrant = (dy > 0) ? ((dx > 0) ? (float)(2 << 15) : (float)(2*(2 << 15)))\n"
"                                  : ((dx > 0) ? 0.0f : (float)(-1*(2 << 15)));\n"
"        if (dy < 0) { dy = -dy; dx = -dx; }\n"
"        if (dx < 0) { float t = dx; dx = dy; dy = -t; }\n"
"        keys[i] = ((ulong)fq_slope_key(quadrant + dy/dx) << 32) | (uint)~(uint)i;\n"
"    }\n"
"\n"
"    int reversed = dot < 0;\n"
"    if (!reversed_border && reversed) return;\n"
"    if (!normal_border && !reversed) return;\n"
"\n"
"    fq_keysort(keys, tmp, sz);\n"
"\n"
"    // compute_lfps: per-point values then sequential cumulative sums\n"
"    global double *fxbuf = g_errs + scr;     // same buffer reuse as the CPU\n"
"    global double *fybuf = g_yfilt + scr;\n"
"    global double *wbuf = g_maxerrs + scr;\n"
"    for (int i = 0; i < sz; i++) {\n"
"        double x = cp[i].x * .5 + 0.5;\n"
"        double y = cp[i].y * .5 + 0.5;\n"
"        int ix = (int)x, iy = (int)y;\n"
"        double W = 1;\n"
"        if (ix > 0 && ix+1 < iw && iy > 0 && iy+1 < ih) {\n"
"            int grad_x = im[iy*istride + ix + 1] - im[iy*istride + ix - 1];\n"
"            int grad_y = im[(iy+1)*istride + ix] - im[(iy-1)*istride + ix];\n"
"            W = sqrt((double)(grad_x*grad_x + grad_y*grad_y)) + 1;\n"
"        }\n"
"        fxbuf[i] = x; fybuf[i] = y; wbuf[i] = W;\n"
"    }\n"
"    fq_lfps lf;\n"
"    lf.Mx  = g_lf + 0*lf_stride + scr;\n"
"    lf.My  = g_lf + 1*lf_stride + scr;\n"
"    lf.Mxx = g_lf + 2*lf_stride + scr;\n"
"    lf.Mxy = g_lf + 3*lf_stride + scr;\n"
"    lf.Myy = g_lf + 4*lf_stride + scr;\n"
"    lf.W   = g_lf + 5*lf_stride + scr;\n"
"    {\n"
"        double sMx = 0, sMy = 0, sMxx = 0, sMyy = 0, sMxy = 0, sW = 0;\n"
"        for (int k = 0; k < sz; k++) {\n"
"            uint srcidx = ~(uint)keys[k];\n"
"            double W = wbuf[srcidx];\n"
"            double fx = fxbuf[srcidx], fy = fybuf[srcidx];\n"
"            sMx += W * fx;\n"
"            sMy += W * fy;\n"
"            sMxx += W * fx * fx;\n"
"            sMxy += W * fx * fy;\n"
"            sMyy += W * fy * fy;\n"
"            sW += W;\n"
"            lf.Mx[k] = sMx; lf.My[k] = sMy; lf.Mxx[k] = sMxx;\n"
"            lf.Mxy[k] = sMxy; lf.Myy[k] = sMyy; lf.W[k] = sW;\n"
"        }\n"
"    }\n"
"\n"
"    // ---- quad_segment_maxima ----\n"
"    int ksz = min(20, sz / 12);\n"
"    if (ksz < 2) return;\n"
"    global double *errs = g_errs + scr;   // fxbuf is dead now, as on the CPU\n"
"    global double *yfilt = g_yfilt + scr;\n"
"    int mid_lo = ksz + 1, mid_hi = sz - ksz - 1;\n"
"    for (int i = 0; i < mid_lo; i++) {\n"
"        int i0 = i - ksz;\n"
"        if (i0 < 0) i0 += sz;\n"
"        { double e; fq_fit_line(&lf, sz, i0, i + ksz, 0, &e, 0); errs[i] = e; }\n"
"    }\n"
"    int N = 2*ksz + 1;\n"
"    for (int i = mid_lo; i <= mid_hi; i++) {\n"
"        int u = i + ksz, l = i - ksz - 1;\n"
"        double Mx = lf.Mx[u] - lf.Mx[l];\n"
"        double My = lf.My[u] - lf.My[l];\n"
"        double Mxx = lf.Mxx[u] - lf.Mxx[l];\n"
"        double Mxy = lf.Mxy[u] - lf.Mxy[l];\n"
"        double Myy = lf.Myy[u] - lf.Myy[l];\n"
"        double W = lf.W[u] - lf.W[l];\n"
"        double Ex = Mx / W, Ey = My / W;\n"
"        double Cxx = Mxx / W - Ex*Ex;\n"
"        double Cxy = Mxy / W - Ex*Ey;\n"
"        double Cyy = Myy / W - Ey*Ey;\n"
"        double root = (double)sqrt((float)((Cxx - Cyy)*(Cxx - Cyy) + 4*Cxy*Cxy));\n"
"        double eig_small = 0.5*(Cxx + Cyy - root);\n"
"        errs[i] = N*eig_small;\n"
"    }\n"
"    for (int i = mid_hi + 1; i < sz; i++) {\n"
"        int i1 = i + ksz;\n"
"        if (i1 >= sz) i1 -= sz;\n"
"        { double e; fq_fit_line(&lf, sz, i - ksz, i1, 0, &e, 0); errs[i] = e; }\n"
"    }\n"
"\n"
"    // 7-tap low-pass with wraparound, then copy back like the CPU memcpy\n"
"    for (int iy = 0; iy < sz; iy++) {\n"
"        double acc = 0;\n"
"        int j = iy - 3;\n"
"        if (j < 0) j += sz;\n"
"        for (int i = 0; i < 7; i++) {\n"
"            acc += errs[j] * qsm_kernel[i];\n"
"            if (++j == sz) j = 0;\n"
"        }\n"
"        yfilt[iy] = acc;\n"
"    }\n"
"    for (int i = 0; i < sz; i++) errs[i] = yfilt[i];\n"
"\n"
"    global int *maxima = g_maxima + scr;\n"
"    global double *maxima_errs = g_maxerrs + scr; // wbuf is dead now\n"
"    int nmaxima = 0;\n"
"    for (int i = 0; i < sz; i++) {\n"
"        double e = errs[i];\n"
"        if (e > errs[i + 1 == sz ? 0 : i + 1] && e > errs[i == 0 ? sz - 1 : i - 1]) {\n"
"            maxima[nmaxima] = i;\n"
"            maxima_errs[nmaxima] = e;\n"
"            nmaxima++;\n"
"        }\n"
"    }\n"
"    if (nmaxima < 4) return;\n"
"\n"
"    if (nmaxima > max_nmaxima) {\n"
"        // quickselect for the (max_nmaxima+1)-th largest error\n"
"        global double *sel = yfilt;\n"
"        for (int i = 0; i < nmaxima; i++) sel[i] = maxima_errs[i];\n"
"        int k = max_nmaxima;\n"
"        int lo = 0, hi = nmaxima - 1;\n"
"        while (lo < hi) {\n"
"            double pivot = sel[(lo + hi) / 2];\n"
"            int i = lo, j = hi;\n"
"            while (i <= j) {\n"
"                while (sel[i] > pivot) i++;\n"
"                while (sel[j] < pivot) j--;\n"
"                if (i <= j) {\n"
"                    double t = sel[i]; sel[i] = sel[j]; sel[j] = t;\n"
"                    i++; j--;\n"
"                }\n"
"            }\n"
"            if (k <= j) hi = j;\n"
"            else if (k >= i) lo = i;\n"
"            else break;\n"
"        }\n"
"        double maxima_thresh = sel[k];\n"
"        int o = 0;\n"
"        for (int in = 0; in < nmaxima; in++) {\n"
"            if (maxima_errs[in] <= maxima_thresh) continue;\n"
"            maxima[o++] = maxima[in];\n"
"        }\n"
"        nmaxima = o;\n"
"    }\n"
"\n"
"    // candidate search over maxima 4-tuples with memoized segment fits\n"
"    global pair_fit_t *memo = g_memo + (ulong)elig_ord[ci] * 16 * 16;\n"
"    for (int i = 0; i < nmaxima*nmaxima; i++) memo[i].computed = 0;\n"
"#define PF_GET(ma, mb, var) \\\n"
"    global pair_fit_t *var = &memo[(ma)*nmaxima + (mb)]; \\\n"
"    if (!var->computed) { \\\n"
"        double lp[4], e, m; \\\n"
"        fq_fit_line(&lf, sz, maxima[ma], maxima[mb], lp, &e, &m); \\\n"
"        var->params[0] = lp[0]; var->params[1] = lp[1]; \\\n"
"        var->params[2] = lp[2]; var->params[3] = lp[3]; \\\n"
"        var->err = e; var->mse = m; \\\n"
"        var->computed = 1; \\\n"
"    }\n"
"    int best_indices[4];\n"
"    double best_error = INFINITY;\n"
"    for (int m0 = 0; m0 < nmaxima - 3; m0++) {\n"
"        int i0 = maxima[m0];\n"
"        for (int m1 = m0+1; m1 < nmaxima - 2; m1++) {\n"
"            PF_GET(m0, m1, pf01);\n"
"            if (pf01->mse > max_line_fit_mse) continue;\n"
"            for (int m2 = m1+1; m2 < nmaxima - 1; m2++) {\n"
"                PF_GET(m1, m2, pf12);\n"
"                if (pf12->mse > max_line_fit_mse) continue;\n"
"                double d = pf01->params[2]*pf12->params[2] + pf01->params[3]*pf12->params[3];\n"
"                if (fabs(d) > max_dot) continue;\n"
"                for (int m3 = m2+1; m3 < nmaxima; m3++) {\n"
"                    PF_GET(m2, m3, pf23);\n"
"                    if (pf23->mse > max_line_fit_mse) continue;\n"
"                    PF_GET(m3, m0, pf30);\n"
"                    if (pf30->mse > max_line_fit_mse) continue;\n"
"                    double err = pf01->err + pf12->err + pf23->err + pf30->err;\n"
"                    if (err < best_error) {\n"
"                        best_error = err;\n"
"                        best_indices[0] = i0;\n"
"                        best_indices[1] = maxima[m1];\n"
"                        best_indices[2] = maxima[m2];\n"
"                        best_indices[3] = maxima[m3];\n"
"                    }\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"#undef PF_GET\n"
"    if (best_error == INFINITY) return;\n"
"    if (!(best_error / sz < max_line_fit_mse)) return;\n"
"\n"
"    // final segment fits and corner intersections\n"
"    double lines[4][4];\n"
"    for (int i = 0; i < 4; i++) {\n"
"        int i0 = best_indices[i];\n"
"        int i1 = best_indices[(i+1)&3];\n"
"        double mse;\n"
"        fq_fit_line(&lf, sz, i0, i1, lines[i], 0, &mse);\n"
"        if (mse > max_line_fit_mse) return;\n"
"    }\n"
"    float qp[4][2];\n"
"    for (int i = 0; i < 4; i++) {\n"
"        double A00 = lines[i][3],  A01 = -lines[(i+1)&3][3];\n"
"        double A10 = -lines[i][2], A11 = lines[(i+1)&3][2];\n"
"        double B0 = -lines[i][0] + lines[(i+1)&3][0];\n"
"        double B1 = -lines[i][1] + lines[(i+1)&3][1];\n"
"        double det = A00 * A11 - A10 * A01;\n"
"        if (fabs(det) < 0.001) return;\n"
"        double W00 = A11 / det, W01 = -A01 / det;\n"
"        double L0 = W00*B0 + W01*B1;\n"
"        qp[i][0] = (float)(lines[i][0] + L0*A00);\n"
"        qp[i][1] = (float)(lines[i][1] + L0*A10);\n"
"    }\n"
"\n"
"    // area and angle sanity checks, as in fit_quad\n"
"    {\n"
"        double area = 0;\n"
"        double length[3], p;\n"
"        for (int i = 0; i < 3; i++) {\n"
"            int ia = i, ib = (i+1) % 3;\n"
"            double ddx = (double)(qp[ib][0] - qp[ia][0]); // float sub, then widen\n"
"            double ddy = (double)(qp[ib][1] - qp[ia][1]);\n"
"            length[i] = sqrt(ddx*ddx + ddy*ddy);\n"
"        }\n"
"        p = (length[0] + length[1] + length[2]) / 2;\n"
"        area += sqrt(p*(p-length[0])*(p-length[1])*(p-length[2]));\n"
"        int idxs[4] = { 2, 3, 0, 2 };\n"
"        for (int i = 0; i < 3; i++) {\n"
"            int ia = idxs[i], ib = idxs[i+1];\n"
"            double ddx = (double)(qp[ib][0] - qp[ia][0]); // float sub, then widen\n"
"            double ddy = (double)(qp[ib][1] - qp[ia][1]);\n"
"            length[i] = sqrt(ddx*ddx + ddy*ddy);\n"
"        }\n"
"        p = (length[0] + length[1] + length[2]) / 2;\n"
"        area += sqrt(p*(p-length[0])*(p-length[1])*(p-length[2]));\n"
"        if (area < 0.95*tag_width*tag_width) return;\n"
"    }\n"
"    for (int i = 0; i < 4; i++) {\n"
"        int i0 = i, i1 = (i+1)&3, i2 = (i+2)&3;\n"
"        double dx1 = (double)(qp[i1][0] - qp[i0][0]);\n"
"        double dy1 = (double)(qp[i1][1] - qp[i0][1]);\n"
"        double dx2 = (double)(qp[i2][0] - qp[i1][0]);\n"
"        double dy2 = (double)(qp[i2][1] - qp[i1][1]);\n"
"        double denom = sqrt((dx1*dx1 + dy1*dy1)*(dx2*dx2 + dy2*dy2));\n"
"        if (denom == 0) return;\n"
"        double cos_dtheta = (dx1*dx2 + dy1*dy2) / denom;\n"
"        if ((cos_dtheta > max_dot || cos_dtheta < -max_dot) || dx1*dy2 < dy1*dx2) return;\n"
"    }\n"
"\n"
"    out[ci].p[0][0] = qp[0][0]; out[ci].p[0][1] = qp[0][1];\n"
"    out[ci].p[1][0] = qp[1][0]; out[ci].p[1][1] = qp[1][1];\n"
"    out[ci].p[2][0] = qp[2][0]; out[ci].p[2][1] = qp[2][1];\n"
"    out[ci].p[3][0] = qp[3][0]; out[ci].p[3][1] = qp[3][1];\n"
"    out[ci].reversed = reversed;\n"
"    out[ci].valid = 1;\n"
"}\n";
